services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: x_frontend
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - x_internal_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: x_backend
    restart: unless-stopped
    networks:
      - x_internal_network
    depends_on:
      - database

  database:
    image: postgres:17.5-alpine3.22
    container_name: x_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dba
      - POSTGRES_PASSWORD=dba
    volumes: 
      - ./database/data:/var/lib/postgresql/data
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - x_internal_network

networks:
  x_internal_network:
    driver: bridge
