FROM rust:1-slim AS dev

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/cargo-bin

RUN cargo install cargo-watch --root /usr/local/cargo-bin

COPY server ./server

WORKDIR /usr/src/app/server

EXPOSE 8080

CMD ["/usr/local/cargo-bin/bin/cargo-watch", "-x", "run --release --all-features"]
