[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.12", features = ["postgres"] }
actix-web = "4.11.0"
actix-cors = "0.7.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
uuid = "1.17.0"
